---
- hosts: local
  roles:
    - role: "dynatrace-oneagent"
      oneagent_action: "install"
      oneagent_key_id: "xxxxxx"
      oneagent_api_token: "xxxxxxxxxxxxxxxxxx"
      oneagent_clean_uninstall: True